services:
  sqldata:
      image: mcr.microsoft.com/azure-sql-edge
      environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=MyPass@word
        - MSSQL_PID=Developer
        - MSSQL_USER=SA
      ports:
        - "1433:1433"

